const products = [
    {
      _id: "1",
      name: "jollof rice",
      image: "/images/test.jpg",
      category: "rice",
      description: "",
      price: 65,
      images: [],
      rating: 4.5,
      numReview: 10,
      countInStock: 6,
    },
    {
      _id: "2",
        name: "fried rice",
        image: "/images/test.jpg",
        category: "rice",
        description: "",
        price: 65,
        images: [],
        rating: 4.5,
        numReview: 10,
        countInStock: 8,
    },
    {
      _id: "3",
      name: "pepsi",
      image: "/images/test.jpg",
      category: "soft-drink",
      description: "",
      price: 65,
      images: [],
      rating: 4.5,
      numReview: 10,
      countInStock: 0,
    },
    {
      _id: "4",
      name: "coca-cola",
      image: "/images/test.jpg",
      category: "soft-drink",
      description: "",
      price: 65,
      images: [],
      rating: 4.5,
      numReview: 10,
      countInStock: 4,
    }
]

module.exports = products